# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ilNS0ld85RvyRcFElUSn9OJ5ccilpDlr
"""

import streamlit as st
import random

# Opciones para dropdowns
technologies = [
    'AI', 'Blockchain', 'IoT', 'AR/VR', 'Quantum Computing', 'Cloud Computing',
    '5G', 'Robotics', 'Edge Computing', 'Cybersecurity', 'Big Data', 'Machine Learning'
]

industries = [
    'healthcare', 'finance', 'education', 'transportation', 'agriculture',
    'real estate', 'e-commerce', 'entertainment', 'manufacturing', 'energy'
]

actions = [
    'transform', 'revolutionize', 'optimize', 'disrupt', 'automate',
    'enhance', 'modernize', 'simplify', 'secure', 'personalize'
]

formats = [
    'a platform', 'a mobile app', 'a SaaS tool', 'an API service',
    'a marketplace', 'a decentralized solution', 'a wearable device',
    'a subscription-based model'
]

def generate_business_idea(tech, industry):
    action = random.choice(actions)
    format_ = random.choice(formats)
    return f"{format_.capitalize()} that uses {tech} to {action} the {industry} industry."

# --- STREAMLIT UI ---
st.title("💡 Startup Idea Generator")

tech = st.selectbox("Choose a technology:", technologies)
industry = st.selectbox("Choose an industry:", industries)

if st.button("Generate Idea"):
    idea = generate_business_idea(tech, industry)
    st.subheader("Your Idea:")
    st.write(idea)